/*

 BOX.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char Box[] =
{
  0xFF,0xFF,0xC3,0xC3,0xA5,0xA5,0x99,0x99,
  0x99,0x99,0xA5,0xA5,0xC3,0xC3,0xFF,0xFF
};

/* End of BOX.C */
